name: Download and push Fedora cloud image to cloud-images registry

on:
  push:
    branches:
      - 'fedora'
  pull_request:
    branches:
      - 'fedora'

jobs:
  download-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ducttape tool from releases
        uses: ducttape-infra/ducttape-install-action@v0.9

      - name: Push image to registry
        env:
          IMAGE_NAME: fedora-cloud
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIR: /home/runner/.local/share/ducttape/base-images
          IMAGE_URL: https://eu.edge.kernel.org/fedora/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
        run: |
          echo "Prepare folders..."
          mkdir -p ${BASE_DIR}

          echo "Downloading image..."
          curl -fSL "${IMAGE_URL}" -o ${BASE_DIR}/${IMAGE_NAME}.qcow2

          echo "Verify ..."
          ls -al ${BASE_DIR}
          sha256sum "${BASE_DIR}/${IMAGE_NAME}.qcow2"

          echo "Pushing image..."
          ducttape push ${IMAGE_NAME} ghcr.io/ducttape-infra/cloud-images/fedora-cloud:43

